{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "002982f0-6e10-46dc-906f-f009011c26e4",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-07-17 22:56:47.829 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-17 22:56:47.834 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-17 22:56:49.041 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run C:\\Users\\Global\\anaconda3\\Lib\\site-packages\\ipykernel_launcher.py [ARGUMENTS]\n",
      "2025-07-17 22:56:49.043 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-17 22:56:49.045 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-17 22:56:49.048 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-17 22:56:49.050 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-17 22:56:49.056 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-17 22:56:49.093 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-17 22:56:49.095 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-17 22:56:49.100 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-17 22:56:49.102 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-17 22:56:49.104 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-17 22:56:49.128 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-17 22:56:49.130 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-17 22:56:49.135 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-17 22:56:49.138 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-17 22:56:49.141 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-17 22:56:49.176 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-17 22:56:49.179 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-17 22:56:49.183 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-17 22:56:49.186 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-17 22:56:49.188 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-17 22:56:49.257 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-17 22:56:49.259 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-17 22:56:49.261 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-17 22:56:49.263 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-17 22:56:49.265 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-17 22:56:49.268 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-17 22:56:49.270 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-17 22:56:50.147 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-17 22:56:50.149 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-17 22:56:50.152 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-17 22:56:50.154 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-17 22:56:50.351 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-17 22:56:50.353 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-17 22:56:50.358 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-17 22:56:50.360 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-17 22:56:50.368 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-17 22:56:50.369 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-17 22:56:50.372 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-17 22:56:50.376 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-17 22:56:50.378 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-17 22:56:50.381 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "DeltaGenerator()"
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Basic data handling\n",
    "import pandas as pd\n",
    "\n",
    "# Streamlit and visualization\n",
    "import streamlit as st\n",
    "import plotly.express as px\n",
    "# Load your dataset\n",
    "df = pd.read_csv(\"Global Superstore Dataset.csv\", encoding='latin1')\n",
    "df.columns = df.columns.str.encode('ascii', 'ignore').str.decode('ascii')\n",
    "df.columns = df.columns.str.strip().str.replace(' ', '_').str.replace('.', '_')\n",
    "# Rename columns for consistency\n",
    "df.columns = df.columns.str.strip().str.replace(\" \", \"_\")\n",
    "\n",
    "# Convert Order Date and Ship Date if needed\n",
    "df['Order_Date'] = pd.to_datetime(df['Order_Date'], errors='coerce')\n",
    "df['Ship_Date'] = pd.to_datetime(df['Ship_Date'], errors='coerce')\n",
    "\n",
    "# Clean Profit and Sales columns\n",
    "df['Profit'] = pd.to_numeric(df['Profit'], errors='coerce')\n",
    "df['Sales'] = pd.to_numeric(df['Sales'], errors='coerce')\n",
    "\n",
    "\n",
    "# Streamlit app starts here\n",
    "st.set_page_config(page_title=\"Global Superstore Dashboard\", layout=\"wide\")\n",
    "st.title(\"📊 Global Superstore Dashboard\")\n",
    "st.markdown(\"Analyze sales, profit, and customer insights interactively.\")\n",
    "\n",
    "# Sidebar Filters\n",
    "st.sidebar.header(\"🔍 Filter the data:\")\n",
    "region = st.sidebar.multiselect(\"Select Region\", df['Region'].dropna().unique(), default=df['Region'].dropna().unique())\n",
    "category = st.sidebar.multiselect(\"Select Category\", df['Category'].dropna().unique(), default=df['Category'].dropna().unique())\n",
    "sub_category = st.sidebar.multiselect(\"Select Sub-Category\", df['Sub_Category'].dropna().unique(), default=df['Sub_Category'].dropna().unique())\n",
    "\n",
    "# Filter the DataFrame\n",
    "filtered_df = df[(df['Region'].isin(region)) &\n",
    "                 (df['Category'].isin(category)) &\n",
    "                 (df['Sub_Category'].isin(sub_category))]\n",
    "\n",
    "\n",
    "# KPIs\n",
    "total_sales = filtered_df['Sales'].sum()\n",
    "total_profit = filtered_df['Profit'].sum()\n",
    "top_customers = filtered_df.groupby('Customer_Name')['Sales'].sum().sort_values(ascending=False).head(5)\n",
    "\n",
    "# Display KPIs\n",
    "col1, col2 = st.columns(2)\n",
    "col1.metric(\"💰 Total Sales\", f\"${total_sales:,.0f}\")\n",
    "col2.metric(\"📈 Total Profit\", f\"${total_profit:,.0f}\")\n",
    "\n",
    "# Sales by Category\n",
    "fig1 = px.bar(filtered_df.groupby('Category')['Sales'].sum().reset_index(),\n",
    "              x='Category', y='Sales', color='Category',\n",
    "              title='💼 Sales by Category')\n",
    "\n",
    "# Profit by Region\n",
    "fig2 = px.pie(filtered_df, names='Region', values='Profit', title='🌍 Profit Distribution by Region')\n",
    "\n",
    "# Top 5 Customers\n",
    "fig3 = px.bar(top_customers.reset_index(), x='Customer_Name', y='Sales',\n",
    "              title='🏆 Top 5 Customers by Sales', color='Sales')\n",
    "\n",
    "# Layout for visuals\n",
    "st.plotly_chart(fig1, use_container_width=True)\n",
    "st.plotly_chart(fig2, use_container_width=True)\n",
    "st.plotly_chart(fig3, use_container_width=True)\n",
    "\n",
    "st.markdown(\"\"\"\n",
    "### 📌 Insights Summary\n",
    "\n",
    "- **Top Performing Regions** and **Categories** are clearly visible from the charts.\n",
    "- The **Top 5 Customers** show where the highest revenue is concentrated.\n",
    "- You can use this dashboard to make **data-driven business decisions** for inventory, marketing, and operations.\n",
    "\n",
    "---\n",
    "\"\"\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
